"""admin management

Revision ID: 2acd8493aa51
Revises: bdc42544909c
Create Date: 2026-07-24 10:57:44.120586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2acd8493aa51'
down_revision: Union[str, Sequence[str], None] = 'bdc42544909c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('admins', sa.Column('username', sa.String(length=255), nullable=True))
    # server_default keeps existing rows valid; role 'super' is assigned on /start from ADMIN_IDS
    op.add_column('admins', sa.Column('role', sa.String(length=20), server_default='admin', nullable=False))
    op.add_column('admins', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'created_at')
    op.drop_column('admins', 'role')
    op.drop_column('admins', 'username')
    op.drop_table('admin_invites')
    # ### end Alembic commands ###
