"""add media_type to reports

Revision ID: bdc42544909c
Revises: 3f65eb8d7214
Create Date: 2026-06-22 18:24:20.986017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc42544909c'
down_revision: Union[str, Sequence[str], None] = '3f65eb8d7214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('media_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'media_type')
    # ### end Alembic commands ###
